# Notebook for tests and examples of model and preprocessing

In this notebook we monitor our progress during practical (coding) phase of our Bachelor thesis.

In [2]:
import numpy as np
# import import_ipynb
# import model

In [4]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [5]:
x.reshape(6,3,1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]],

       [[16],
        [17],
        [18]]])

In [7]:
x.reshape(*x.shape, -1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]],

       [[16],
        [17],
        [18]]])

### Model training

**Phase 1:** Training model with static dataset (not generated during training)

**Phase 2:** Training model with dataset, which is generated during training phase